// <auto-generated />
using System;
using AttendanceSystemPersistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AttendanceSystemPersistence.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20210311182841_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.3");

            modelBuilder.Entity("AttendanceSystemApp.Models.HomeWork", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("HomeWorks");
                });

            modelBuilder.Entity("AttendanceSystemApp.Models.Lecture", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("CourseName")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("LecturerId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("LecturerId");

                    b.ToTable("Lectures");
                });

            modelBuilder.Entity("AttendanceSystemApp.Models.Lecturer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Lecturers");
                });

            modelBuilder.Entity("AttendanceSystemApp.Models.Student", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<double>("Grade")
                        .HasColumnType("REAL");

                    b.Property<Guid?>("HomeWorkId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("LectureId")
                        .HasColumnType("TEXT");

                    b.Property<int>("LecturesCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<int>("SkipCount")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("HomeWorkId");

                    b.HasIndex("LectureId");

                    b.ToTable("Students");
                });

            modelBuilder.Entity("AttendanceSystemApp.Models.Lecture", b =>
                {
                    b.HasOne("AttendanceSystemApp.Models.Lecturer", null)
                        .WithMany("Lectures")
                        .HasForeignKey("LecturerId");
                });

            modelBuilder.Entity("AttendanceSystemApp.Models.Student", b =>
                {
                    b.HasOne("AttendanceSystemApp.Models.HomeWork", "HomeWork")
                        .WithMany()
                        .HasForeignKey("HomeWorkId");

                    b.HasOne("AttendanceSystemApp.Models.Lecture", null)
                        .WithMany("Students")
                        .HasForeignKey("LectureId");

                    b.Navigation("HomeWork");
                });

            modelBuilder.Entity("AttendanceSystemApp.Models.Lecture", b =>
                {
                    b.Navigation("Students");
                });

            modelBuilder.Entity("AttendanceSystemApp.Models.Lecturer", b =>
                {
                    b.Navigation("Lectures");
                });
#pragma warning restore 612, 618
        }
    }
}
